/*

	Books

  ---------------------------------------------------------------
  VERSION 1.2

  - Spread out data into separate files.

  ---------------------------------------------------------------
  NOTES

  - 'identifier' is used by readingApps.js to create Bible
      app links
  - 'nameAbbr' is used by getEastonsArray() to match against
      Easton's references.
  -  `wordCount`s are from the KJV translation.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*/

import { chapterWordCounts } from './books.chapterWordCounts';
import { chapterYears } from './books.chapterYears';
import { verseCounts } from './books.verseCounts';

// prettier-ignore
export const books = [
  {
    id:                 1,
    name:               'Genesis',
    nameShort:          'Genesis',
    nameAbbr:           'Gen',
    identifier:         'GEN',
    chapterCount:       50,
    wordCount:          38265,
    chapterWordCounts:  chapterWordCounts[1],
    chapterYears:       chapterYears[1],
    verseCounts:        verseCounts[1],
    // verseWordCounts:    verseWordCounts[1],
  },
  {
    id:                 2,
    name:               'Exodus',
    nameShort:          'Exodus',
    nameAbbr:           'Exod',
    identifier:         'EXO',
    chapterCount:       40,
    wordCount:          32684,
    chapterWordCounts:  chapterWordCounts[2],
    chapterYears:       chapterYears[2],
    verseCounts:        verseCounts[2],
    // verseWordCounts:    verseWordCounts[2],
  },
  {
    id:                 3,
    name:               'Leviticus',
    nameShort:          'Levit.',
    nameAbbr:           'Lev',
    identifier:         'LEV',
    chapterCount:       27,
    wordCount:          24543,
    chapterWordCounts:  chapterWordCounts[3],
    chapterYears:       chapterYears[3],
    verseCounts:        verseCounts[3],
    // verseWordCounts:    verseWordCounts[3],
  },
  {
    id:                 4,
    name:               'Numbers',
    nameShort:          'Numbers',
    nameAbbr:           'Num',
    identifier:         'NUM',
    chapterCount:       36,
    wordCount:          32895,
    chapterWordCounts:  chapterWordCounts[4],
    chapterYears:       chapterYears[4],
    verseCounts:        verseCounts[4],
    // verseWordCounts:    verseWordCounts[4],
  },
  {
    id:                 5,
    name:               'Deuteronomy',
    nameShort:          'Deuter.',
    nameAbbr:           'Deut',
    identifier:         'DEU',
    chapterCount:       34,
    wordCount:          28352,
    chapterWordCounts:  chapterWordCounts[5],
    chapterYears:       chapterYears[5],
    verseCounts:        verseCounts[5],
    // verseWordCounts:    verseWordCounts[5],
  },
  {
    id:                 6,
    name:               'Joshua',
    nameShort:          'Joshua',
    nameAbbr:           'Josh',
    identifier:         'JOS',
    chapterCount:       24,
    wordCount:          18852,
    chapterWordCounts:  chapterWordCounts[6],
    chapterYears:       chapterYears[6],
    verseCounts:        verseCounts[6],
    // verseWordCounts:    verseWordCounts[6],
  },
  {
    id:                 7,
    name:               'Judges',
    nameShort:          'Judges',
    nameAbbr:           'Judg',
    identifier:         'JDG',
    chapterCount:       21,
    wordCount:          18966,
    chapterWordCounts:  chapterWordCounts[7],
    chapterYears:       chapterYears[7],
    verseCounts:        verseCounts[7],
    // verseWordCounts:    verseWordCounts[7],
  },
  {
    id:                 8,
    name:               'Ruth',
    nameShort:          'Ruth',
    nameAbbr:           'Ruth',
    identifier:         'RUT',
    chapterCount:       4,
    wordCount:          2574,
    chapterWordCounts:  chapterWordCounts[8],
    chapterYears:       chapterYears[8],
    verseCounts:        verseCounts[8],
    // verseWordCounts:    verseWordCounts[8],
  },
  {
    id:                 9,
    name:               '1 Samuel',
    nameShort:          '1 Samuel',
    nameAbbr:           '1 Sam',
    identifier:         '1SA',
    chapterCount:       31,
    wordCount:          25047,
    chapterWordCounts:  chapterWordCounts[9],
    chapterYears:       chapterYears[9],
    verseCounts:        verseCounts[9],
    // verseWordCounts:    verseWordCounts[9],
  },
  {
    id:                 10,
    name:               '2 Samuel',
    nameShort:          '2 Samuel',
    nameAbbr:           '2 Sam',
    identifier:         '2SA',
    chapterCount:       24,
    wordCount:          20599,
    chapterWordCounts:  chapterWordCounts[10],
    chapterYears:       chapterYears[10],
    verseCounts:        verseCounts[10],
    // verseWordCounts:    verseWordCounts[10],
  },
  {
    id:                 11,
    name:               '1 Kings',
    nameShort:          '1 Kings',
    nameAbbr:           '1 Kgs',
    identifier:         '1KI',
    chapterCount:       22,
    wordCount:          24512,
    chapterWordCounts:  chapterWordCounts[11],
    chapterYears:       chapterYears[11],
    verseCounts:        verseCounts[11],
    // verseWordCounts:    verseWordCounts[11],
  },
  {
    id:                 12,
    name:               '2 Kings',
    nameShort:          '2 Kings',
    nameAbbr:           '2 Kgs',
    identifier:         '2KI',
    chapterCount:       25,
    wordCount:          23521,
    chapterWordCounts:  chapterWordCounts[12],
    chapterYears:       chapterYears[12],
    verseCounts:        verseCounts[12],
    // verseWordCounts:    verseWordCounts[12],
  },
  {
    id:                 13,
    name:               '1 Chronicles',
    nameShort:          '1 Chron.',
    nameAbbr:           '1 Chr',
    identifier:         '1CH',
    chapterCount:       29,
    wordCount:          20365,
    chapterWordCounts:  chapterWordCounts[13],
    chapterYears:       chapterYears[13],
    verseCounts:        verseCounts[13],
    // verseWordCounts:    verseWordCounts[13],
  },
  {
    id:                 14,
    name:               '2 Chronicles',
    nameShort:          '2 Chron.',
    nameAbbr:           '2 Chr',
    identifier:         '2CH',
    chapterCount:       36,
    wordCount:          26069,
    chapterWordCounts:  chapterWordCounts[14],
    chapterYears:       chapterYears[14],
    verseCounts:        verseCounts[14],
    // verseWordCounts:    verseWordCounts[14],
  },
  {
    id:                 15,
    name:               'Ezra',
    nameShort:          'Ezra',
    nameAbbr:           'Ezra',
    identifier:         'EZR',
    chapterCount:       10,
    wordCount:          7440,
    chapterWordCounts:  chapterWordCounts[15],
    chapterYears:       chapterYears[15],
    verseCounts:        verseCounts[15],
    // verseWordCounts:    verseWordCounts[15],
  },
  {
    id:                 16,
    name:               'Nehemiah',
    nameShort:          'Nehem.',
    nameAbbr:           'Neh',
    identifier:         'NEH',
    chapterCount:       13,
    wordCount:          10480,
    chapterWordCounts:  chapterWordCounts[16],
    chapterYears:       chapterYears[16],
    verseCounts:        verseCounts[16],
    // verseWordCounts:    verseWordCounts[16],
  },
  {
    id:                 17,
    name:               'Esther',
    nameShort:          'Esther',
    nameAbbr:           'Est',
    identifier:         'EST',
    chapterCount:       10,
    wordCount:          5630,
    chapterWordCounts:  chapterWordCounts[17],
    chapterYears:       chapterYears[17],
    verseCounts:        verseCounts[17],
    // verseWordCounts:    verseWordCounts[17],
  },
  {
    id:                 18,
    name:               'Job',
    nameShort:          'Job',
    nameAbbr:           'Job',
    identifier:         'JOB',
    chapterCount:       42,
    wordCount:          18098,
    chapterWordCounts:  chapterWordCounts[18],
    chapterYears:       chapterYears[18],
    verseCounts:        verseCounts[18],
    // verseWordCounts:    verseWordCounts[18],
  },
  {
    id:                 19,
    name:               'Psalms',
    nameShort:          'Psalms',
    nameAbbr:           'Ps',
    identifier:         'PSA',
    chapterCount:       150,
    wordCount:          42684,
    chapterWordCounts:  chapterWordCounts[19],
    chapterYears:       chapterYears[19],
    verseCounts:        verseCounts[19],
    // verseWordCounts:    verseWordCounts[19],
  },
  {
    id:                 20,
    name:               'Proverbs',
    nameShort:          'Proverbs',
    nameAbbr:           'Prov',
    identifier:         'PRO',
    chapterCount:       31,
    wordCount:          15038,
    chapterWordCounts:  chapterWordCounts[20],
    chapterYears:       chapterYears[20],
    verseCounts:        verseCounts[20],
    // verseWordCounts:    verseWordCounts[20],
  },
  {
    id:                 21,
    name:               'Ecclesiastes',
    nameShort:          'Eccles.',
    nameAbbr:           'Ecc',
    identifier:         'ECC',
    chapterCount:       12,
    wordCount:          5580,
    chapterWordCounts:  chapterWordCounts[21],
    chapterYears:       chapterYears[21],
    verseCounts:        verseCounts[21],
    // verseWordCounts:    verseWordCounts[21],
  },
  {
    id:                 22,
    name:               'Song of Songs',
    nameShort:          'Song',
    nameAbbr:           'Song',
    identifier:         'SNG',
    chapterCount:       8,
    wordCount:          2658,
    chapterWordCounts:  chapterWordCounts[22],
    chapterYears:       chapterYears[22],
    verseCounts:        verseCounts[22],
    // verseWordCounts:    verseWordCounts[22],
  },
  {
    id:                 23,
    name:               'Isaiah',
    nameShort:          'Isaiah',
    nameAbbr:           'Isa',
    identifier:         'ISA',
    chapterCount:       66,
    wordCount:          37039,
    chapterWordCounts:  chapterWordCounts[23],
    chapterYears:       chapterYears[23],
    verseCounts:        verseCounts[23],
    // verseWordCounts:    verseWordCounts[23],
  },
  {
    id:                 24,
    name:               'Jeremiah',
    nameShort:          'Jeremiah',
    nameAbbr:           'Jer',
    identifier:         'JER',
    chapterCount:       52,
    wordCount:          42654,
    chapterWordCounts:  chapterWordCounts[24],
    chapterYears:       chapterYears[24],
    verseCounts:        verseCounts[24],
    // verseWordCounts:    verseWordCounts[24],
  },
  {
    id:                 25,
    name:               'Lamentations',
    nameShort:          'Lament.',
    nameAbbr:           'Lam',
    identifier:         'LAM',
    chapterCount:       5,
    wordCount:          3411,
    chapterWordCounts:  chapterWordCounts[25],
    chapterYears:       chapterYears[25],
    verseCounts:        verseCounts[25],
    // verseWordCounts:    verseWordCounts[25],
  },
  {
    id:                 26,
    name:               'Ezekiel',
    nameShort:          'Ezekiel',
    nameAbbr:           'Ezek',
    identifier:         'EZK',
    chapterCount:       48,
    wordCount:          39401,
    chapterWordCounts:  chapterWordCounts[26],
    chapterYears:       chapterYears[26],
    verseCounts:        verseCounts[26],
    // verseWordCounts:    verseWordCounts[26],
  },
  {
    id:                 27,
    name:               'Daniel',
    nameShort:          'Daniel',
    nameAbbr:           'Dan',
    identifier:         'DAN',
    chapterCount:       12,
    wordCount:          11603,
    chapterWordCounts:  chapterWordCounts[27],
    chapterYears:       chapterYears[27],
    verseCounts:        verseCounts[27],
    // verseWordCounts:    verseWordCounts[27],
  },
  {
    id:                 28,
    name:               'Hosea',
    nameShort:          'Hosea',
    nameAbbr:           'Hos',
    identifier:         'HOS',
    chapterCount:       14,
    wordCount:          5174,
    chapterWordCounts:  chapterWordCounts[28],
    chapterYears:       chapterYears[28],
    verseCounts:        verseCounts[28],
    // verseWordCounts:    verseWordCounts[28],
  },
  {
    id:                 29,
    name:               'Joel',
    nameShort:          'Joel',
    nameAbbr:           'Joel',
    identifier:         'JOL',
    chapterCount:       3,
    wordCount:          2033,
    chapterWordCounts:  chapterWordCounts[29],
    chapterYears:       chapterYears[29],
    verseCounts:        verseCounts[29],
    // verseWordCounts:    verseWordCounts[29],
  },
  {
    id:                 30,
    name:               'Amos',
    nameShort:          'Amos',
    nameAbbr:           'Amos',
    identifier:         'AMO',
    chapterCount:       9,
    wordCount:          4216,
    chapterWordCounts:  chapterWordCounts[30],
    chapterYears:       chapterYears[30],
    verseCounts:        verseCounts[30],
    // verseWordCounts:    verseWordCounts[30],
  },
  {
    id:                 31,
    name:               'Obadiah',
    nameShort:          'Obadiah',
    nameAbbr:           'Obad',
    identifier:         'OBA',
    chapterCount:       1,
    wordCount:          669,
    chapterWordCounts:  chapterWordCounts[31],
    chapterYears:       chapterYears[31],
    verseCounts:        verseCounts[31],
    // verseWordCounts:    verseWordCounts[31],
  },
  {
    id:                 32,
    name:               'Jonah',
    nameShort:          'Jonah',
    nameAbbr:           'Jonah',
    identifier:         'JON',
    chapterCount:       4,
    wordCount:          1320,
    chapterWordCounts:  chapterWordCounts[32],
    chapterYears:       chapterYears[32],
    verseCounts:        verseCounts[32],
    // verseWordCounts:    verseWordCounts[32],
  },
  {
    id:                 33,
    name:               'Micah',
    nameShort:          'Micah',
    nameAbbr:           'Mic',
    identifier:         'MIC',
    chapterCount:       7,
    wordCount:          3152,
    chapterWordCounts:  chapterWordCounts[33],
    chapterYears:       chapterYears[33],
    verseCounts:        verseCounts[33],
    // verseWordCounts:    verseWordCounts[33],
  },
  {
    id:                 34,
    name:               'Nahum',
    nameShort:          'Nahum',
    nameAbbr:           'Nah',
    identifier:         'NAM',
    chapterCount:       3,
    wordCount:          1284,
    chapterWordCounts:  chapterWordCounts[34],
    chapterYears:       chapterYears[34],
    verseCounts:        verseCounts[34],
    // verseWordCounts:    verseWordCounts[34],
  },
  {
    id:                 35,
    name:               'Habakkuk',
    nameShort:          'Habakkuk',
    nameAbbr:           'Hab',
    identifier:         'HAB',
    chapterCount:       3,
    wordCount:          1475,
    chapterWordCounts:  chapterWordCounts[35],
    chapterYears:       chapterYears[35],
    verseCounts:        verseCounts[35],
    // verseWordCounts:    verseWordCounts[35],
  },
  {
    id:                 36,
    name:               'Zephaniah',
    nameShort:          'Zephan.',
    nameAbbr:           'Zeph',
    identifier:         'ZEP',
    chapterCount:       3,
    wordCount:          1616,
    chapterWordCounts:  chapterWordCounts[36],
    chapterYears:       chapterYears[36],
    verseCounts:        verseCounts[36],
    // verseWordCounts:    verseWordCounts[36],
  },
  {
    id:                 37,
    name:               'Haggai',
    nameShort:          'Haggai',
    nameAbbr:           'Hag',
    identifier:         'HAG',
    chapterCount:       2,
    wordCount:          1130,
    chapterWordCounts:  chapterWordCounts[37],
    chapterYears:       chapterYears[37],
    verseCounts:        verseCounts[37],
    // verseWordCounts:    verseWordCounts[37],
  },
  {
    id:                 38,
    name:               'Zechariah',
    nameShort:          'Zechar.',
    nameAbbr:           'Zech',
    identifier:         'ZEC',
    chapterCount:       14,
    wordCount:          6443,
    chapterWordCounts:  chapterWordCounts[38],
    chapterYears:       chapterYears[38],
    verseCounts:        verseCounts[38],
    // verseWordCounts:    verseWordCounts[38],
  },
  {
    id:                 39,
    name:               'Malachi',
    nameShort:          'Malachi',
    nameAbbr:           'Mal',
    identifier:         'MAL',
    chapterCount:       4,
    wordCount:          1781,
    chapterWordCounts:  chapterWordCounts[39],
    chapterYears:       chapterYears[39],
    verseCounts:        verseCounts[39],
    // verseWordCounts:    verseWordCounts[39],
  },
  {
    id:                 40,
    name:               'Matthew',
    nameShort:          'Matthew',
    nameAbbr:           'Matt',
    identifier:         'MAT',
    chapterCount:       28,
    wordCount:          23684,
    chapterWordCounts:  chapterWordCounts[40],
    chapterYears:       chapterYears[40],
    verseCounts:        verseCounts[40],
    // verseWordCounts:    verseWordCounts[40],
  },
  {
    id:                 41,
    name:               'Mark',
    nameShort:          'Mark',
    nameAbbr:           'Mark',
    identifier:         'MRK',
    chapterCount:       16,
    wordCount:          15166,
    chapterWordCounts:  chapterWordCounts[41],
    chapterYears:       chapterYears[41],
    verseCounts:        verseCounts[41],
    // verseWordCounts:    verseWordCounts[41],
  },
  {
    id:                 42,
    name:               'Luke',
    nameShort:          'Luke',
    nameAbbr:           'Luke',
    identifier:         'LUK',
    chapterCount:       24,
    wordCount:          25939,
    chapterWordCounts:  chapterWordCounts[42],
    chapterYears:       chapterYears[42],
    verseCounts:        verseCounts[42],
    // verseWordCounts:    verseWordCounts[42],
  },
  {
    id:                 43,
    name:               'John',
    nameShort:          'John',
    nameAbbr:           'John',
    identifier:         'JHN',
    chapterCount:       21,
    wordCount:          19094,
    chapterWordCounts:  chapterWordCounts[43],
    chapterYears:       chapterYears[43],
    verseCounts:        verseCounts[43],
    // verseWordCounts:    verseWordCounts[43],
  },
  {
    id:                 44,
    name:               'Acts',
    nameShort:          'Acts',
    nameAbbr:           'Acts',
    identifier:         'ACT',
    chapterCount:       28,
    wordCount:          24246,
    chapterWordCounts:  chapterWordCounts[44],
    chapterYears:       chapterYears[44],
    verseCounts:        verseCounts[44],
    // verseWordCounts:    verseWordCounts[44],
  },
  {
    id:                 45,
    name:               'Romans',
    nameShort:          'Romans',
    nameAbbr:           'Rom',
    identifier:         'ROM',
    chapterCount:       16,
    wordCount:          9422,
    chapterWordCounts:  chapterWordCounts[45],
    chapterYears:       chapterYears[45],
    verseCounts:        verseCounts[45],
    // verseWordCounts:    verseWordCounts[45],
  },
  {
    id:                 46,
    name:               '1 Corinthians',
    nameShort:          '1 Corin.',
    nameAbbr:           '1 Cor',
    identifier:         '1CO',
    chapterCount:       16,
    wordCount:          9462,
    chapterWordCounts:  chapterWordCounts[46],
    chapterYears:       chapterYears[46],
    verseCounts:        verseCounts[46],
    // verseWordCounts:    verseWordCounts[46],
  },
  {
    id:                 47,
    name:               '2 Corinthians',
    nameShort:          '2 Corin.',
    nameAbbr:           '2 Cor',
    identifier:         '2CO',
    chapterCount:       13,
    wordCount:          6065,
    chapterWordCounts:  chapterWordCounts[47],
    chapterYears:       chapterYears[47],
    verseCounts:        verseCounts[47],
    // verseWordCounts:    verseWordCounts[47],
  },
  {
    id:                 48,
    name:               'Galatians',
    nameShort:          'Galat.',
    nameAbbr:           'Gal',
    identifier:         'GAL',
    chapterCount:       6,
    wordCount:          3084,
    chapterWordCounts:  chapterWordCounts[48],
    chapterYears:       chapterYears[48],
    verseCounts:        verseCounts[48],
    // verseWordCounts:    verseWordCounts[48],
  },
  {
    id:                 49,
    name:               'Ephesians',
    nameShort:          'Ephes.',
    nameAbbr:           'Eph',
    identifier:         'EPH',
    chapterCount:       6,
    wordCount:          3022,
    chapterWordCounts:  chapterWordCounts[49],
    chapterYears:       chapterYears[49],
    verseCounts:        verseCounts[49],
    // verseWordCounts:    verseWordCounts[49],
  },
  {
    id:                 50,
    name:               'Philippians',
    nameShort:          'Philipp.',
    nameAbbr:           'Phil',
    identifier:         'PHP',
    chapterCount:       4,
    wordCount:          2183,
    chapterWordCounts:  chapterWordCounts[50],
    chapterYears:       chapterYears[50],
    verseCounts:        verseCounts[50],
    // verseWordCounts:    verseWordCounts[50],
  },
  {
    id:                 51,
    name:               'Colossians',
    nameShort:          'Coloss.',
    nameAbbr:           'Col',
    identifier:         'COL',
    chapterCount:       4,
    wordCount:          1979,
    chapterWordCounts:  chapterWordCounts[51],
    chapterYears:       chapterYears[51],
    verseCounts:        verseCounts[51],
    // verseWordCounts:    verseWordCounts[51],
  },
  {
    id:                 52,
    name:               '1 Thessalonians',
    nameShort:          '1 Thess.',
    nameAbbr:           '1 Th',
    identifier:         '1TH',
    chapterCount:       5,
    wordCount:          1837,
    chapterWordCounts:  chapterWordCounts[52],
    chapterYears:       chapterYears[52],
    verseCounts:        verseCounts[52],
    // verseWordCounts:    verseWordCounts[52],
  },
  {
    id:                 53,
    name:               '2 Thessalonians',
    nameShort:          '2 Thess.',
    nameAbbr:           '2 Th',
    identifier:         '2TH',
    chapterCount:       3,
    wordCount:          1022,
    chapterWordCounts:  chapterWordCounts[53],
    chapterYears:       chapterYears[53],
    verseCounts:        verseCounts[53],
    // verseWordCounts:    verseWordCounts[53],
  },
  {
    id:                 54,
    name:               '1 Timothy',
    nameShort:          '1 Timo.',
    nameAbbr:           '1 Tim',
    identifier:         '1TI',
    chapterCount:       6,
    wordCount:          2244,
    chapterWordCounts:  chapterWordCounts[54],
    chapterYears:       chapterYears[54],
    verseCounts:        verseCounts[54],
    // verseWordCounts:    verseWordCounts[54],
  },
  {
    id:                 55,
    name:               '2 Timothy',
    nameShort:          '2 Timo.',
    nameAbbr:           '2 Tim',
    identifier:         '2TI',
    chapterCount:       4,
    wordCount:          1666,
    chapterWordCounts:  chapterWordCounts[55],
    chapterYears:       chapterYears[55],
    verseCounts:        verseCounts[55],
    // verseWordCounts:    verseWordCounts[55],
  },
  {
    id:                 56,
    name:               'Titus',
    nameShort:          'Titus',
    nameAbbr:           'Tit',
    identifier:         'TIT',
    chapterCount:       3,
    wordCount:          896,
    chapterWordCounts:  chapterWordCounts[56],
    chapterYears:       chapterYears[56],
    verseCounts:        verseCounts[56],
    // verseWordCounts:    verseWordCounts[56],
  },
  {
    id:                 57,
    name:               'Philemon',
    nameShort:          'Philemon',
    nameAbbr:           'Phm',
    identifier:         'PHM',
    chapterCount:       1,
    wordCount:          430,
    chapterWordCounts:  chapterWordCounts[57],
    chapterYears:       chapterYears[57],
    verseCounts:        verseCounts[57],
    // verseWordCounts:    verseWordCounts[57],
  },
  {
    id:                 58,
    name:               'Hebrews',
    nameShort:          'Hebrews',
    nameAbbr:           'Heb',
    identifier:         'HEB',
    chapterCount:       13,
    wordCount:          6897,
    chapterWordCounts:  chapterWordCounts[58],
    chapterYears:       chapterYears[58],
    verseCounts:        verseCounts[58],
    // verseWordCounts:    verseWordCounts[58],
  },
  {
    id:                 59,
    name:               'James',
    nameShort:          'James',
    nameAbbr:           'Jam',
    identifier:         'JAS',
    chapterCount:       5,
    wordCount:          2304,
    chapterWordCounts:  chapterWordCounts[59],
    chapterYears:       chapterYears[59],
    verseCounts:        verseCounts[59],
    // verseWordCounts:    verseWordCounts[59],
  },
  {
    id:                 60,
    name:               '1 Peter',
    nameShort:          '1 Peter',
    nameAbbr:           '1 Pet',
    identifier:         '1PE',
    chapterCount:       5,
    wordCount:          2475,
    chapterWordCounts:  chapterWordCounts[60],
    chapterYears:       chapterYears[60],
    verseCounts:        verseCounts[60],
    // verseWordCounts:    verseWordCounts[60],
  },
  {
    id:                 61,
    name:               '2 Peter',
    nameShort:          '2 Peter',
    nameAbbr:           '2 Pet',
    identifier:         '2PE',
    chapterCount:       3,
    wordCount:          1553,
    chapterWordCounts:  chapterWordCounts[61],
    chapterYears:       chapterYears[61],
    verseCounts:        verseCounts[61],
    // verseWordCounts:    verseWordCounts[61],
  },
  {
    id:                 62,
    name:               '1 John',
    nameShort:          '1 John',
    nameAbbr:           '1 Jn',
    identifier:         '1JN',
    chapterCount:       5,
    wordCount:          2516,
    chapterWordCounts:  chapterWordCounts[62],
    chapterYears:       chapterYears[62],
    verseCounts:        verseCounts[62],
    // verseWordCounts:    verseWordCounts[62],
  },
  {
    id:                 63,
    name:               '2 John',
    nameShort:          '2 John',
    nameAbbr:           '2 Jn',
    identifier:         '2JN',
    chapterCount:       1,
    wordCount:          298,
    chapterWordCounts:  chapterWordCounts[63],
    chapterYears:       chapterYears[63],
    verseCounts:        verseCounts[63],
    // verseWordCounts:    verseWordCounts[63],
  },
  {
    id:                 64,
    name:               '3 John',
    nameShort:          '3 John',
    nameAbbr:           '3 Jn',
    identifier:         '3JN',
    chapterCount:       1,
    wordCount:          294,
    chapterWordCounts:  chapterWordCounts[64],
    chapterYears:       chapterYears[64],
    verseCounts:        verseCounts[64],
    // verseWordCounts:    verseWordCounts[64],
  },
  {
    id:                 65,
    name:               'Jude',
    nameShort:          'Jude',
    nameAbbr:           'Jude',
    identifier:         'JUD',
    chapterCount:       1,
    wordCount:          608,
    chapterWordCounts:  chapterWordCounts[65],
    chapterYears:       chapterYears[65],
    verseCounts:        verseCounts[65],
    // verseWordCounts:    verseWordCounts[65],
  },
  {
    id:                 66,
    name:               'Revelation',
    nameShort:          'Revelat.',
    nameAbbr:           'Rev',
    identifier:         'REV',
    chapterCount:       22,
    wordCount:          11995,
    chapterWordCounts:  chapterWordCounts[66],
    chapterYears:       chapterYears[66],
    verseCounts:        verseCounts[66],
    // verseWordCounts:    verseWordCounts[66],
  },
] as const;
